branches:
  only:
    - master
    - development

language: node_js
node_js:
- '0.12'

sudo: false

addons:
  ssh_known_hosts: vsg-xebaci.cyoncloud.com

cache:
  directories:
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_96f6e50b1323_key -iv $encrypted_96f6e50b1323_iv
  -in deploy.enc -out deploy -d
- chmod 600 deploy

install:
- npm install -g grunt-cli
- npm install

script:
- grunt build

after_success: ./deploy.sh

